baseURL = "https://renalias.net/"
languageCode = "en-us"
title = "Oscar Renalias"
enableRobotsTXT = true

[params]
  description = "Oscar Renalias' personal and professional site. Cloud, architecture and technology transformation topics for technology leaders."
